on:
  push:
    branches:
    - "master"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "master"
        destination_branch: "develop"
        pr_title: "BACKMERGE ${{ github.ref }} into develop"
        pr_body: "*An automated PR*"
        pr_reviewer: "wei,worker"             # Comma-separated list (no spaces)
        pr_assignee: "wei,worker"             # Comma-separated list (no spaces)
        github_token: ${{ secrets.GITHUB_TOKEN }}